Improved logging, fix unicode error, include_dir buildrun
Kattis/problemtools pull request #209
Opened 2022-07-12 21:31 UTC by incaseoftrouble

Hi,

I'm using problemtools as library in a larger script to automate deployment of lectures. In that process I found some things I thought needed fixing. I tried to keep changes small and can also make them a bit more consistent. Depending on your wishes, I might address some more things in the future :-)

Mainly, I introduced a bit more consistent logging and added the possibility of having `build/run` in the include_dir. I used this for some java validators where a common build script lies in an included dir.

Closes #201

2023-05-01 12:55 UTC, pehrsoderman requested changes
There seems to be some debugging related changes left in this pr...

2023-05-01 12:55 UTC, pehrsoderman commented on problemtools/verifyproblem.py
> +        #     sys.stdout.write('%s' % '\b \b' * (len(msg)))
Why is this commented out?

2023-11-25 10:41 UTC, incaseoftrouble commented
Hey, sorry, I somehow completely forgot that this is open. Should I update this to the current release?

2023-11-25 17:13 UTC, pehrsoderman commented
@incaseoftrouble Please do a rebase

2023-12-05 13:01 UTC, incaseoftrouble commented
Just as a remark on that: My schedule is absolutely full, I put this into my calendar for February. (But I put it in!)

2024-02-12 11:47 UTC, incaseoftrouble commented
Moved to #253

2024-02-12 11:47 UTC, closed without merging