Markdown support
Kattis/problemtools pull request #274
Opened 2024-08-17 15:23 UTC by Matistjati

This PR is not done, at the moment this serves as a TODO-list

supported:
- commonmark-style images
- svg for pdf (TODO: check if it works with latex). needs to be specced
- "common" footnotes. needs to be specced. how much? (probably not)
- "common" tables. needs to be specced
- inline and display math with \$a+b\$ and \$\$a+b\$\$. needs to be specced

TODO:
- nicer md->pdf (sample) tables
- make a "maximal" example
- debug overflowing line on team coding (more testing)
- fix all dependencies (remove python-markdown, add pandoc and rsvg-convert)
- discuss problemname, nextsample, etc with fredrik
- pdf images
- svg for html

not planned to be added in this PR:
- tex -> html using pandoc (remove plastex)

2025-03-12 23:05 UTC, Matistjati commented
@pehrsoderman want to take a look? I think this PR is ready for a review. Here are the statements i tested it on:

https://github.com/Matistjati/kattis-markdown-examples

In general, most statements don't look perfect right off the bat, mostly because they come from their own markdown dialect. However, I believe that all ugliness can be fixed by small tweaks.

2025-03-18 10:27 UTC, gkreitz requested changes
I took a pass over this. As mentioned on slack, it seems like pandoc makes no security guarantees on html output and recommends using a sanitizer (https://pandoc.org/chunkedhtml-demo/19-a-note-on-security.html). That's gonna get messy, I'm not a huge fan of any of the python options. If anyone happens to look at this PR and has any recommendations, feel free to chime in.

Looking through, I think I spotted a number of places where we need to be more careful with escaping stuff we inject (problem name, sample, and just as an extra precaution, problem id). I'm not quite sure how to do that cleanly, t.b.h. If I understand the code correctly, it seems like when pandoc goes from markdown to pdf, it goes via LaTeX, which means that inserting plain LaTeX in the markdown works. That dual-step translation makes me wonder how to sanely escape stuff like `\` or `$` when we inject it (or, as an extreme example, the sample of a problem about parsing latex :)).

2025-03-18 10:27 UTC, gkreitz commented on problemtools/statement_common.py
> +    names = config.get("name")
This will break after #286, but you're probably aware of that. :)

2025-03-18 10:27 UTC, gkreitz commented on problemtools/statement_common.py
> +            return subprocess.run(command, capture_output=True, text=True,
A bit of a corner case, but what happens if the sample contains latex (or, more likely,  latex control characters like `$`)? I'm assuming pandoc won't escape that when converting HTML to markdown, so won't that then later mess up the PDF rendering once you've injected this markdown into the document and are trying to `pandoc` into a pdf?

2025-03-18 10:27 UTC, gkreitz commented on problemtools/statement_common.py
> +                                            "text": data})
`data` probably needs to be escaped (for both markdown *and* latex, I guess)?

2025-03-18 10:27 UTC, gkreitz commented on problemtools/statement_common.py
> +            lines.append(f"""<div class="{line_type}"><pre>{data}</pre></div>""")
`data` needs to be escaped (for html, so that's easy at least).

2025-04-03 01:39 UTC, Matistjati commented on problemtools/problem2pdf.py
> +                    os.path.join(os.path.dirname(__file__), '../templates/markdown_pdf'),
It was in fact not needed.

2025-04-04 01:56 UTC, Matistjati commented on problemtools/statement_common.py
> +    names = config.get("name")
Yup, talked with Rasmus and Hugo to hopefully work something out

2025-04-07 20:09 UTC, Matistjati commented on problemtools/md2html.py
> +    if FOOTNOTES_STRING in html_template:
Done

2025-04-07 21:08 UTC, Matistjati commented
Known issues:
- (PDF) Samples might overflow
![image](https://github.com/user-attachments/assets/b370a4f9-972c-4c80-b358-fa30fed34119)
- (PDF) If you use all but the simplest possible table, the outline will not work properly. I tried a workaround, which works for some tables, but we will need a LaTeX wiz (not me) to account for all tables using macros. See https://github.com/jgm/pandoc/issues/922
![image](https://github.com/user-attachments/assets/4cdbf384-83cd-4052-905b-9983504e5e7b)
- (HTML) If you place `{{remainingsamples}}` in the text, you end up with something like
![image](https://github.com/user-attachments/assets/ea685556-c01d-4127-bab5-ce1ad350f232)
- SVGs are currently not supported. Will be fixed in a follow-up PR.
- Does not support multipass samples

2025-04-08 00:21 UTC, Matistjati commented on problemtools/statement_common.py
> +            lines.append(f"""<div class="{line_type}"><pre>{data}</pre></div>""")
Done

2025-04-08 00:21 UTC, Matistjati commented on problemtools/statement_common.py
> +                                            "text": data})
Done

2025-04-08 00:22 UTC, Matistjati commented on problemtools/statement_common.py
> +            return subprocess.run(command, capture_output=True, text=True,
Painstakingly, this has been fixed.

2025-04-08 11:17 UTC, gkreitz reviewed
I took another pass over it, as requested. This is getting close to ready for merging. The main problem I see are a couple of places where we need to escape latex characters (the rendering path of markdown -> latex -> pdf that pandoc does is funky...).

2025-04-08 11:17 UTC, gkreitz commented on problemtools/statement_common.py
> +        "\\": "\\textbackslash{}",
Nitpick/feature suggestion: Python has "raw string literals" for exactly this use case. If you write these strings as `r'\textbackslash{}'` you avoid double escaping almost all the backslashes here.

2025-04-08 11:17 UTC, gkreitz commented on problemtools/statement_common.py
> +                    curr_vspace + ascii_char_widths[line[0]] < space_per_row:
It looks to me like this would crash for characters not in `ascii_char_widths`. I don't think it's feasible to build a table of all possible characters. IIRC from typography, I think the best you can do for a character not in the table is to look up with width of the letter m.

2025-04-08 11:17 UTC, gkreitz commented on problemtools/statement_common.py
> +    ascii_char_widths = {' ': 3.33333, '!': 3.2, '"': 6.2, '#': 9.6, '$': 5.9, '%': 9.6, '&': 9.0, "'": 3.2, '(': 4.5, ')': 4.5, '*': 5.8, '+': 9.0, ',': 6.2, '-': 6.5, '.': 5, '/': 5.8, '0': 5.8, '1
Ouch, what a table to build. Don't we want to use a monospace font for this, though?

2025-04-08 11:17 UTC, gkreitz commented on problemtools/statement_common.py
> +                                %(text)s \\
This looks like it will still break if there are latex control characters in the sample?

2025-04-09 07:17 UTC, Matistjati commented on problemtools/statement_common.py
> +                                %(text)s \\
Fixed by depending on normal tex -> pdf in problemtools

2025-04-09 07:17 UTC, Matistjati commented on problemtools/statement_common.py
> +    ascii_char_widths = {' ': 3.33333, '!': 3.2, '"': 6.2, '#': 9.6, '$': 5.9, '%': 9.6, '&': 9.0, "'": 3.2, '(': 4.5, ')': 4.5, '*': 5.8, '+': 9.0, ',': 6.2, '-': 6.5, '.': 5, '/': 5.8, '0': 5.8, '1
Fixed by depending on normal tex -> pdf in problemtools

2025-04-09 07:18 UTC, Matistjati commented on problemtools/statement_common.py
> +                    curr_vspace + ascii_char_widths[line[0]] < space_per_row:
Fixed by depending on normal tex -> pdf in problemtools

2025-05-13 08:44 UTC, gkreitz approved these changes
Looks good, code just had two small things. Tests failing due to UUID should be fixed by #307 merging (and then rebasing on that).

For example problems, I'm ok with merging this as-is, but if so we should do a follow-up soon where we convert the problems to 2023-07.

2025-05-14 14:15 UTC, Matistjati commented on tests/test_markdown.py
> +    # nh3 will escape &, < and >
You are right, fixed

2025-05-14 14:15 UTC, Matistjati commented on problemtools/statement_util.py
> +        lines.append(f"""<div class="{line_type}"><pre>{html.escape(data)}</pre></div>""")
Yup, fixed

2025-05-14 15:34 UTC, merged